# You can specify multiple profile-specific YAML documents in a single file by using a spring.profiles key
# to indicate when the document applies.


---
spring:
    profiles:
        active: dev
    application:
        name: tri-metr-java

logging: # spring boot considers either file or path property, not both.
    file: sdk-java-spring.log
#    path: logs/spring-boot/

info:
    project:
        version: #project.version#

---
spring:
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by gradle when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#

logging: # spring boot considers either file or path property, not both.
    file: sdk-java-spring.log


# ===================================================================
# Application specific properties (JIRA and METRICS credentials)
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration
#
# ===================================================================

application:
    jira:
        jiraEndPoint: http://jira.ald.int.westgroup.com
        username: Sergei.Zheleznov
        password: AlkaDavalka123

        unitId: 828
        apiAccessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1MDI0NTQxMzQsImV4cCI6MTUwNTA4MjEzNCwiaWF0IjoxNTAyNDU0MTM0LCJpc3MiOiJUUiBEZWxpdmVyeSBIZWFsdGggUG9ydGFsLiBTQU5EQk9YIiwianRpIjoiYjRmM2VjZGQtMDI0YS00NmY4LWI4N2UtNjJlYzIwNTM1ODZjIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IlNlcmdlaV9aaGVsZXpub3ZAZXBhbS5jb20iLCJ0b2tlbl90eXBlIjoiQWNjZXNzIiwidW5pdF9kZXZlbG9wZXIiOiI4MjgiLCJ1bml0X2FkbWluIjoiODI4In0.NGTUTYttoFvnDJXXrzJpbujvvZiyjeFauuBjZOHNCGg
        apiEndPoint: https://sandbox.tri-metr.projects.epam.com/backend

        rapidViewId: 4

